#! /bin/bash

killall -q picom
killall -q sxhkd
eww kill

sxhkd &
picom &
eww daemon
eww open bar
xwallpaper --zoom ~/.wallpapers


bspc monitor -d 1 2 3 4 5 6 7

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config focused_border_color    "#E43F5A"
bspc config normal_border_color     "#162447"

bspc config top_padding         20
bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
